title: hobby-selector
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2023-08-01"
steps:
  - title: Randomise your hobbies!
